### ISSUE TITLE
App invite calling deep link activity two times

### ISSUE THREAD

**Issue by varunbadgujar** [googlesamples/google-services#141]
i have added appinvite in my app and handling deeplink activity manually whenever user click on install button from the mail then deeplink activity is launched now when i exit the application and again launch the app from app icon then alongwith main activity deep link activity is also launched.

Means i am getting values in Result callback
onResult(AppInviteInvitationResult result)   

How i can clear the result intent once i have used it ?

**Comment by samtstern** [comment]
If you are calling `getInvitation` in `onCreate` of your main Activity, you may want to guard it like this so it only happens once:

```java
@Override
public void onCreate(Bundle savedInstanceState) {
   // ...

   if (savedInstanceState == null) {
     AppInvite.AppInviteApi.getInvitation(...);
   }
}
```

**Comment by varunbadgujar** [comment]
during app launch it will call first, but my scenario is when app is lanched from mail box then its gives intent values now i close the app from back button and again launch the app from app icon then i get same intent.

i have refer google service app invite sample, also this sample also has same problem.

from your answer first time i will get null so it looks for app invite invitation and once i will close the app, then will again launch from app icon in that case we will again get saveInstanceState to null  then we will again get invitation.

**Comment by samtstern** [comment]
@varunbadgujar we have confirmed this is a bug, thanks for reporting!

Since it appears this occurs exactly twice (in my testing), you could call getInvitation a second time with no callback (null or empty) to work around the bug.

**Comment by felipe-silvestre-movile** [comment]
This bug was already fixed?

**Comment by samtstern** [comment]
@felipe-silvestre-movile a few releases ago there was a bug where this would happen for other reasons.  The current release is working as intended, and app developers should follow the steps above.

**Comment by anothem** [comment]
I'm still seeing this (or something similar), on 9.0.2.
Had to do a second call with `AppInvite.AppInviteApi.getInvitation(googleApiClient, null, false);` after the one with the callback to prevent it from being captured a second time.
