### ISSUE TITLE
Android Google Sign In Nothing Happen If Use Add Account

### ISSUE THREAD

**Issue by vwijaya03** [googlesamples/google-services#358]
Here's the case:

1. Press Sign In Button
2. Add Account
3. Insert Email and Password
4. Waiting Checking Info
5. Screen like a black hover, and nothing happened
6. When i press, the screen it back to normal but return null at first time and return error code 8, when i pressed sign in button again i get the data

I have already put my SHA-1 and use the correct server_client_id.
If i have already signed in user, the google sign in works, the problem only at first time login with no account or create account.

compile 'com.google.android.gms:play-services-drive:11.8.0'
compile 'com.google.android.gms:play-services-auth:11.8.0'

Any suggestion for this problem ? Thanks

**Comment by huynhtansi** [comment]
Same issue!

**Comment by Rahulrsannidhi** [comment]
The issue is not resolved yet.The same case is happening for most of the android application in the play store.Please suggest on this.

**Comment by mydamyda** [comment]
+1:

Same issue.

**Comment by aaronj1335** [comment]
What version of Google Play services (i.e. com.google.android.gms) is running on the devices where you're observing this? 12.2.21?

**Comment by Rahulrsannidhi** [comment]
Checking on Samsung Note 8 and Samsung s8 with google play version 12.2.21.

**Comment by vwijaya03** [comment]
Mine Asus Zenfone 2 with Google Play services version 12.2.21 (270-188803320)

**Comment by mydamyda** [comment]
I am implementing a login library.
So I am working as a "com.android.library" plugin.

Nexus 5X with Google Play services version 12.2.21 (440-188803320).

using 'com.google.android.gms:play-services-auth:11.8.0'.

**Comment by AJRaju** [comment]
Can someone please help on this issue. It works perfectly fine from second time ie. when the user has logged in with device google account. I face issue only for the first time when i use "use another account" during login.
 I am using "com.google.android.gms:play-services-auth:12.0.0" .  
Any help appreciated. Thanks.

**Comment by samtstern** [comment]
Hey all,

Thank you for reporting this issue.  We are aware of it and taking it seriously.  A fix for this issue will come over-the-air through an update to Google Play services, there's not much you can do to mitigate this right now besides just wait.

**Comment by coolwd10** [comment]
If this doesn't solve your problem, you may want to clear the cache and data of Google Play Store, Google App and all other Google apps. A factory reset would be the short way out in this case.

2. App/OS incompatibility - a somewhat rare scenario would be when your app or OS is outdated and can't fit into the Google Services framework. Many a times tech enthusiasts install the latest version of this or that and this is one of the major causes of incompatibility. You could,

A. Look for system updates

B. Try installing a different ROM .

C. Do a factory reset.

3. Firewall wars - If you have an AV with anti-theft and have tripped some feature, you may be prevented from adding or deleting accounts. Apps that work as system administrators can also do this. Alternatively, you may have simply given a firewall too much freedom to block your access to Google. Solutions -

A. Find culprit app and uninstall it.

4. Chinese ROMs - A good many Google services are not open to Chinese users. So if you've got a Chinese device with Google Play Services thrown in, the OS would have trouble working with it. This is because Chinese forks of Android are often not meant to work with Google accounts. To solve -

A. Root and flash an International ROM (or US/EU/UK) ROM.

B. Try installing a different version of Google Play Services. This probably won't work but if you absolutely don't want to go through the hassle of rooting, this may be your only option.

5. Google Play Store or Services corrupted - Rather rare but can happen if you've ever installed the app yourself through a non Play Store source. To solve, simply uninstall and reinstall. Now "simply" may well mean searching through backups and dependable sites ("dependable") for alternative versions of the Services and Play Store app.

6. Network issues - Enough said. Fix the internet.

Hope these help.

**Comment by coolwd10** [comment]
Problems with existing cache /app data - As someone suggested, this can be solved by going to Settings<installed apps/Apps<Google Play Services<Clear Cache / Clear Data. You may have to force stop the app before you can proceed.

**Comment by vwijaya03** [comment]
@coolwd10 i have tried your solution and still cant.

**Comment by jom16antonio** [comment]
Having the same issue here. Has there been any investigation on what causes this? Also, the onActivityResult does not return a result when a new account is logged in.

**Comment by vwijaya03** [comment]
@jom16antonio not yet, still need to wait

**Comment by niczm25** [comment]
I am using Genymotion's Google Nexus 5 api23, with Google Play service version 12.2.21 (470-188803320)

**Comment by jom16antonio** [comment]
Hi any update regarding this issue? Maybe TS can add a label help_wanted?

**Comment by vwijaya03** [comment]
how to do that hehehe ?

**Comment by vwijaya03** [comment]
@samtstern any new update sir ?

**Comment by otopba** [comment]
Same issue! =(

**Comment by jjssoftware** [comment]
I see this is also affecting Android TV in both Nougat 7.0 on a real Android TV (Sony Bravia) and also emulated Android TV running Oreo 8.0. Google Play Services 12.2.21 (876-188803320) here. No amount of force close or clearing data fixes this..makes testing the development of a new app totally ropey :)

**Comment by JonathanMelgoza** [comment]
I cant wait for ever, i have clients..

**Comment by vwijaya03** [comment]
For my client, i told them to press the login again after add account. @JonathanMelgoza

**Comment by vwijaya03** [comment]
@samtstern thank you 😃

**Comment by adonisv79** [comment]
@samtstern is there a date available as to when this will be made available? or even a public notice which we can use to prove to clients that this is an Android/Google specific issue and not caused by our individual mobile apps?

**Comment by leoacevedo** [comment]
Same here, very interested

**Comment by JonathanMelgoza** [comment]
You should give us an estimated date for solution..

**Comment by dharmik94** [comment]
Same Issue

**Comment by vcsomor** [comment]
@samtstern is this issue officially reported somewhere?
I have to refer this to my documentation at least.

**Comment by Abhishekkmr789** [comment]
@samtstern can you please let us know when we can expect an update for Google Services?

**Comment by samtstern** [comment]
Sorry all I just can't provide an estimated date for when the version with the fix will go out, I am not ignoring you!

**Comment by PierLuca93** [comment]
Same issue here.

I did a bit of debugging and it looks like when you're taken back to the app with the black hover, onActivityResult isn't called by play services.
Only after i press, the black hover goes away and onActivityResult is called, but with result code 0 and all the account data (email, token, etc) are null.
Then if i try again choosing the same account just added from the dialog everything is fine.
Tried also with playservices version 15.0.0 but the issue is still there.

**Comment by tejasparekh** [comment]
Facing the same issue. Any update from Google?

**Comment by Xiaojuanmao** [comment]
+1

**Comment by leonardomontes** [comment]
same issue here...

**Comment by kapilsukhyani** [comment]
+1

**Comment by jom16antonio** [comment]
Android P beta has now beed shown in Google IO '18. Is there any news on how to solve this issue? Im sure this is evident to Android phones, tv etc that has login.
Are we just going to ignore that the Goggle Sign in has flaw?

**Comment by UttamPanchasara** [comment]
Facing same issue as mentioned by @koushikchoudhury0

**Comment by shahankitt** [comment]
@samtstern : It would be great if you could provide an update on this issue or refer to any official documentation highlighting the same issue. I'm baffled that Google is taking so long to fix such a high priority issue which is not allowing the first time users to use the app. I'm sure this is being looked into but at least an ETA can help us manage the expectations and behavior of real paying users on our app.. Also it would be highly appreciated if you or your team could share any workaround whatsoever to unblock the huge set of users affected by this.

**Comment by JonathanMelgoza** [comment]
It's urgent! I cant believe any fix release yet..

**Comment by Anwera64** [comment]
I'm also facing the same issue

**Comment by rafaldziuryk** [comment]
ugly and not perfect but working for me. 

On black hover `onStart()` (`onResume()` not called)  in our Activity will be called. Then I refresh Activity and mark tryAutoLogin flag as true. In newIntent I check if user has any Google Account and call login function. In my case, it shows Account Picker (with just created account)

```
class SelectAccountActivity : AppCompatActivity() {

var tryAutoLogin = false

override fun onStart()
    {
        super.onStart()
        val m = getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        m.appTasks.firstOrNull()?.let {
            if (it.taskInfo.topActivity.className.endsWith("SignInActivity"))
            {
                tryAutoLogin = true
                startActivity(Intent(this, SelectAccountActivity::class.java).apply {
                    addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
                    addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
                })
            }
        }
    }

    override fun onNewIntent(intent: Intent?)
    {
        val accountManager = getSystemService(Context.ACCOUNT_SERVICE) as AccountManager
        val anyGoogleAccount = accountManager.accounts.any { it.type == "com.google" }
        when (tryAutoLogin && anyGoogleAccount)
        {
            true ->
            {
                tryToLogin()
                tryAutoLogin = false
            }
        }
    }

}

**Comment by patelrohan22** [comment]
Here is the another work around by which i got solution until we get release update from google.

As we know onActivityResult() does not called only when user add new account, but onRestart() and start() method get called. 

Below is the code to open google concent screen to picked up account or add new account.
```
Intent signInIntent = loginHandler.mGoogleSignInClient.getSignInIntent();
        activity.startActivityForResult(signInIntent, RC_GET_TOKEN);
```

Before calling above code I keep currently registered google accounts count. i.e 3 accounts registered in my device.

Once user complete add new account process, onStart() method will get call and here i checked again google account count by below code:

` Account[] googleAccounts = AccountManager.get(activity).getAccountsByType("com.google");

        if (googleAccounts != null && googleAccounts.length > 0) {
            if (lastGoogleAccounts == 0) {
                lastGoogleAccounts = googleAccounts.length;
            } else {
                if (googleAccounts.length > lastGoogleAccounts) {
                 // do login
}` 

if new count is > last count, it means new account is registered and redirect to home screen.

**Comment by leonardbos** [comment]
@patelrohan22 I tried to implement your solution but can't figure out what you mean with lastGoogleAccounts?

**Comment by thomc2nf** [comment]
Hope this problem will be fixed soon. My client reported to me for acceptance test : D!

**Comment by patelrohan22** [comment]
@leonardbos lastGoogleAccounts which hold current registered google accounts count in your device before adding new account.

**Comment by mkamals** [comment]
Same issue for me as well. I am using Google Play Services version 15.0.1, waiting for the fix with new release of Google Play services.

**Comment by ppdany** [comment]
same issue here 🙋🏻‍♂️

**Comment by mirha495** [comment]
Is there a planned date when this is supposed to be fixed?

**Comment by 1136066873** [comment]
same issue here 🙋🏻‍♂️...
Has this problem not been resolved yet?

**Comment by thetestspecimen** [comment]
I also have this problem. 

I have been looking into the other options above to work around this, but to get the number of accounts on the device from AccountManager requires a "dangerous" user-permission, and so will require the users consent, which is not ideal. 

An ETA on a fix for this really is needed. This issue was opened on 17th March. That makes it almost 3 months without a fix, or an ETA!

**Comment by 1136066873** [comment]
In fact, I found a way to log in to a Google account, but this approach is conditional;
The way is to use Android AccountManager to launch the login to the Google account interface;
requirement is:
First: The current project signature information is consistent with the system signature information.
Second: The current device integrates GMS.

This way you can indeed log in to your Google account.
reference:  [https://github.com/1136066873/FuckGooFourth](url)

**Comment by arthlimchiu** [comment]
A workaround that I'm currently using is just using this approach.

```
private lateinit var credential: GoogleAccountCredential

override fun onCreate(savedInstanceState: Bundle?) {
        ...

        credential = GoogleAccountCredential.usingOAuth2(this, SCOPES.toCollection(ArrayList()))
                .setBackOff(ExponentialBackOff())
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        when (requestCode) {
            REQUEST_ACCOUNT_PICKER -> {
                if (resultCode == RESULT_OK && data != null && data.extras != null) {
                    val accountName = data.getStringExtra(AccountManager.KEY_ACCOUNT_NAME)
                    if (accountName != null) {
                        // accountName is the email
                        credential.selectedAccountName = accountName
                    }
                }
            }
        }
    }
```

**Comment by DilerxD** [comment]
Hi, they fixed :D ty so much Google Team :D

**Comment by antonRooseleer** [comment]
@DilerxD Do you need to update anything for the fix? I just tried it and it still seems broken for me.

**Comment by DilerxD** [comment]
@antonRooseleer no, i only compile the app and prove :(.

**Comment by bonchangkoo** [comment]
It is still not fixed...

**Comment by vwijaya03** [comment]
@DilerxD already fixed the bug ?

**Comment by DilerxD** [comment]
@bonchangkoo  @vwijaya03 i already tested on s8 with android 8.0 i dont know if for that i dont have the problem, tomorrow i would try with android simulator :D. Sorry for dont answerd right now.

**Comment by mkamals** [comment]
@koushikchoudhury0  @DilerxD  I tested it in Oreo and the issue is still not fixed.

**Comment by akshaykumar0291** [comment]
Is there any update regarding this issue?

**Comment by jjssoftware** [comment]
Perhaps when Google declare this is fixed we can then assume it is then fixed and confirm that by testing. That's if they can ever be bothered to fix it. Until that happens I'm going to assume this is permanently broken.

**Comment by ganjasmara** [comment]
Hi, I've found some bugs (using play-services-auth v15.0.1)

  - Everytime you go to Google new account activity (you dont have to add the new account, just press back) it always invalidate the previous sign-in activity (resultCode == 0 or RESULT_CANCELED in onActivityResult), hence if you call getResult from Task it will trigger ApiException
  - If you actually add the new account and continue the login process, it will still considered as a continuation of previous sign-in activity (not sure about this), which resulted in RESULT_CANCELED & ApiException too

**Comment by DilerxD** [comment]
Hi guys, for this update we need this version 	
Google Play Store 10.7.19 by Google LLC --> July 3, 2018
of Google Play :(

**Comment by ganjasmara** [comment]
@DilerxD err sorry but I've already updated the Google Play Store (not sure what the correlation of this to the issue) & its still bugged

**Comment by DilerxD** [comment]
Hi everyone, really i dont know how Google fix this issue, i have 2 Samsung Galaxy s8, one with the issue fixed and another dont. Really this days i saw what app is diferent or i dont know, but is an update of something :(.

**Comment by samtstern** [comment]
This issue is being fixed by an update to the **Google Play services** application.  This is an automatic update that happens in the background.  Since there are more than a billion Android devices in the world that run this application we do the rollouts in stages.  That's why you may see the fix on some devices and not others.

I will update this thread when it's 100% rolled out.

**Comment by jjssoftware** [comment]
At last, a Google response addressing all the "it's fixed, it's not fixed" rubbish. Thank you.

**Comment by DilerxD** [comment]
@samtstern ty for the information :D

**Comment by georgeRCluj** [comment]
@samtstern I tested on my Samsung SM-J330F (Android 7.0, API 24), google play services are updated and the issue still persists... I do not see any update option. Any news on when this automatic update will take polace?

**Comment by darwinphi** [comment]
Still can't add a google account in my phone. I can't update apps. Play Store is not working.

**Comment by mkamals** [comment]
@samtstern Thanks for the info about the issue being fixed by an update.

I tried checking this issue with Redmi Note 3 which has Google Play Services v12.8.72, the issue is fixed in this device. Whereas when I checked the same issue in Nexus5 which has Google Play Services v12.6.85, the issue is still not resolved. 

I hope this issue will be resolved for everyone when the update is rolled out completely so developers don't need to panic about this.

**Comment by samtstern** [comment]
@mkamals as you noticed, some devices do have the fixed version.  We had an unrelated issue with that version though which has caused the rollout to be delayed more than expected.  Hoping to be able to announce a fix here soon!

**Comment by samtstern** [comment]
Well it's been a wonderful journey on this issue with you all, but today we can finally close it. 

After some fun hurdles, v12.8.74 was pushed to 100% yesterday.  This should mean you should stop seeing this issue now or in a day or two once everyone's devices get the update to Google Play services. 

We know this was a painful one.  Although it may seem really slow, we got the fix out as quick as we could in a safe way.  Thanks for all your reports and patience.

**Comment by dvaai** [comment]
SAMSUNG GALAXY S8 HAS THIS ISSUE CAN SOME ONE HELP

**Comment by karsai1993** [comment]
Dear @samtstern , thanks for you update on this but today I uninstalled my app and installed again but the problem remains. My Google Services version is correct (12.8.74). Could please suggest what I should do? Thanks, László

**Comment by karsai1993** [comment]
For my case, the problem disappeared after adding SHA-1 and SHA-256 of both debug and release keystore values to the Firebase Console.

**Comment by jackyq2015** [comment]
@karsai1993 I had the same version with you. How can you add SHA-256 to console? I only have SHA-1.

**Comment by karsai1993** [comment]
Hi @jackyq2015 ,
For debug values, you have to run this command: keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android. It should give you SHA-256 as well. As for release values, you have to replace the fields of the above command with the release keystore related values.

This is where you can add fingerprint (SHA-256 as well):
![image](https://user-images.githubusercontent.com/15123875/43636788-5d669eea-9713-11e8-965f-0bd01fd5c7d9.png)

Best regards,
László

**Comment by jackyq2015** [comment]
@karsai1993 Added the SHA256 from the console. But the problem remains. I use debug mode so added the debug alias fingerprint.

**Comment by DilerxD** [comment]
@jackyq2015 can you add an image of the screen of add account because with the patch the "splash screen" change :D

**Comment by jackyq2015** [comment]
@DilerxD , Please review:
![add_account](https://user-images.githubusercontent.com/10520203/43660604-808beab4-972d-11e8-98c1-442a4206734e.png)

**Comment by DilerxD** [comment]
@jackyq2015 the screen when you tap the button add account

**Comment by jackyq2015** [comment]
@DilerxD Unfortunately, I cannot even bring the screen I posted above even I uninstall the app and clean up the cache. Will post the add account screen as soon as I can. Instead of the screenshot is there any way you can think of to check the correctness of the version?

**Comment by mokhtar1234** [comment]
I can't sign in to my Google play account on tv box T95D

**Comment by kashifo** [comment]
It's not resolved yet, but closed.

**Comment by yeahse** [comment]
> It's not resolved yet, but closed.

Why got closed?

**Comment by DennyWeinberg** [comment]
> SAMSUNG GALAXY S8 HAS THIS ISSUE CAN SOME ONE HELP

I have a client who is facing that issue!

**Comment by p-funky** [comment]
@samtstern hi there. I am wondering if there is a final word on this issue because I seem to be stuck on something around this.

**Comment by p-funky** [comment]
Apparently, adding an application logo to my project in the Google Cloud Platform console resolved the issue I was having. See https://www.youtube.com/watch?v=Ay9F6WHfnkU for more context.
