### ISSUE TITLE
Google Sign In dialog stuck loading when YouTube Scope is requested.

### ISSUE THREAD

**Issue by josemontiel** [googlesamples/google-services#413]
* Device: Pixel XL
  * OS version: Q Beta 4
  * SDK version: 28
  * [Android] Google Play Services version: 17.0.0
  
###  Describe the problem:

When testing Google Sign In and requesting Youtube's Readonly scope, the sign in dialog gets stuck loading after selecting a Google Account.

No errors are thrown or logs printed on Logcat, and it works perfectly if YouTube scope is left out.

**Comment by samtstern** [comment]
@josemontiel thanks for reporting this, I will file a bug internally.  Have you been able to reproduce this on multiple devices / accounts or just one?

**Comment by josemontiel** [comment]
Thank you @samtstern , I have been able to reproduce this issue 100% of the times, I have also discarded it being an account-related issue since doing it using the web-flow works well and works on iOS as well.

**Comment by davidsun** [comment]
Hey, josemontiel@, can you explain what scopes your app is asking for? Thanks!

**Comment by josemontiel** [comment]
Sure @davidsun , right now the scopes being requested are:

- email
- profile
- https://www.googleapis.com/auth/youtube.readonly

**Comment by samtstern** [comment]
@josemontiel just FYI it looks like @davidsun and team were able to reproduce this issue in our internal test app, which is the first step to a fix.  Thank you for noticing it!

**Comment by WorkmaiEric** [comment]
Watching the issue here, we are experiencing the same problem. Hope it gets fixed soon

**Comment by samtstern** [comment]
Hey everyone.  The team found the source of the issue and is fixing it on the backend, so a change should roll out over the next few weeks.  Thanks for your help and your patience!

**Comment by josemontiel** [comment]
Thank you very much for taking a look into this issue @samtstern , please keep us posted when the fix rolls out!

**Comment by samtstern** [comment]
This should now be fixed, thanks all!

**Comment by TomTietze** [comment]
> This should now be fixed, thanks all!

Hey @samtstern 

unfortunately the problem was not fixed. I experience the same issue when I requesting a scope, regardless of which scope (the same for Youtube, Drive and Google Fit). The problem occurs only for users which have a "googlemail" domain. After the change to "gmail" it will work again. Does Google no longer support "googlemail" domains in the Google sign-up API?

Greetings,
Tom

**Comment by samtstern** [comment]
@TomTietze I will ask around.

**Comment by raphaelluchini** [comment]
> > This should now be fixed, thanks all!
> 
> Hey @samtstern
> 
> unfortunately the problem was not fixed. I experience the same issue when I requesting a scope, regardless of which scope (the same for Youtube, Drive and Google Fit). The problem occurs only for users which have a "googlemail" domain. After the change to "gmail" it will work again. Does Google no longer support "googlemail" domains in the Google sign-up API?
> 
> Greetings,
> Tom

I am also facing the same problems with googlemail domains. Specially using google fit.

**Comment by dknchris** [comment]
Not fixed. I'm facing the same issue with googlemail domain users when they try to connect the app with Google Drive. The consent dialog just keeps loading forever.

**Comment by vashisthg** [comment]
My users are complaining of same errors for connecting with Google fit. This dialog loads forever. 
cc @samtstern

**Comment by Alimiel** [comment]
I also see the same problem. I am trying to request YouTube Data API scope for testing and it gets stuck indefinitely on loading screen on emulator. I am using gmail to authenticate.

**Comment by sonnyky** [comment]
I came across this ticket when browsing for a similar issue. I'm stuck when requesting for drive.readonly scope. And my account uses gmail. not googlemail, so perhaps the original issue is still not fixed?

**Comment by angelgonzaf** [comment]
Im trying with scope https://www.googleapis.com/auth/youtube and the loading stuck is still happening. I also use gmail, not googlemail. It seems that the issue is not fixed yet!

**Comment by hsoni228** [comment]
I am facing this issue with requesting google drive permissions, https://www.googleapis.com/auth/drive.file
I am using it in android and the screen is stuck in a loading state, please help, I followed the google doc completely, but nothing helped.

**Comment by JamesBlyth** [comment]
I'm also suffering from this issue with the Google Fit history scopes.

**Comment by Kongreen** [comment]
У меня нет цели исправить то что создали другие. Кто в процессе развития ресурса по алчной халатности допустил деградацию утопию цифрового потока информации не задумываясь о последствиях, по причине мне гуд а там будь. что будет. А нет я вот столкнулся с гранью реальности и не собираюсь терпеть и молчать когда тебе в душу лезут, без твоего согласия отбирают варую личное сокровенное семейный мирок кокой он есть. И это факт противостояния с системой как карма для меня. Вызов на действия доводя до решения вопроса чистый поток интернет ресурс созданный в результате развития человечества для нынешнего и будущего поколения. За это можно горы свернуть если шребет не переломят. Миг жизни он создан чтоб прожить его достойно и дать низменность терору и осквернении человека недопустимо есть чувство собственного достоинства и о чём знаю я сам не доказывая я выполняя свою защиту от воздействия. Да накипело, эмоции это полезно иногда высказаться. Я не имею полной информации и я могу ошибаться в осуждении ПО, но на это есть причины, если неправ извинюсь. Если прав то исправься не создавай проблемы от своего деяния 👨‍👩‍👧‍👦🤝🌍

**Comment by junieberry** [comment]
I'm experiencing same issue when I request permission for Google Fit Api. It wortked well before, but all of a sudden it get stuck.

**Comment by jcasier** [comment]
Still happening with Google Fit on Android 10 & 11

**Comment by Anirban-Chand** [comment]
I'm facing the same issue for the last 5 long days. Checked all kinda firebase config, API console settings but didn't get to any solution. Production and test apps both are under the same project in API console and Firebase. Googling all day but have no clue how to fix.

**Comment by Rashid-Khabeer** [comment]
I am also facing same issue, I am giving `https://www.googleapis.com/auth/youtube` in scopes of google sign in, I want to use youtube api I added sha1 and sha256 in my firebase app and also enabled youtubeapi data api v3 in google cloud console, but login process is stuck in loading screen after google account selection

**Comment by lucifernipun22** [comment]
@samtstern still facing issue with google fit.Thank you!
